### ISSUE TITLE
update dependencies

### ISSUE THREAD

**Issue by splitbrain** [ForceUniverse/bountyhunter#1]
I'm trying to use this in flutter but installing fails because the dependencies seem to be too strict/out of date:

`Because every version of flutter_test from sdk depends on logging 0.11.3+1 and every version of bountyhunter depends on logging ^0.9.0, flutter_test from sdk is incompatible with bountyhunter.`

Any chance this could be updated to use a newer logging package?

**Comment by jorishermans** [comment]
Sure, no problem for me.

**Comment by jorishermans** [comment]
I updated the package, can you test this again and let me know if it works for you.

Thanks!

**Comment by splitbrain** [comment]
Yeah, dependency resolution works again. Thank you very much for the fast response.
